import { createSlice } from "@reduxjs/toolkit";

export const PlayersInAgencySlice = createSlice({
  name: "PlayersInAgencySlice",
  initialState: {
    playersInAgencyArray: [
      {
        id: "ddc92652-a3e4-4518-b374-5cf589ec1e7c",
        firstName: "Richard",
        surName: "Attah",
        Age: "28",
        position: "GK",
        Nationality: "Ghana",
        CountryCode: "GH",
        jerseyNumber: "1",
        image: "/richard attah.jpeg",
        clubName: "Accra Hearts of Oak SC",
        clubLogo: "/Accra_hearts_of_oak_sc.png",
        preferredFoot: "Right",
        height: "1.5",
        marketValue: "83K",
        contractExpiryDate: "2024/11/13",
      },
      {
        id: "4efaea39-3cfa-409a-929c-03fe6074aad9",
        firstName: "Benjamin",
        surName: "Bature",
        Age: "26",
        CountryCode: "GH",
        Nationality: "Ghana",
        position: "CF",
        jerseyNumber: "21",
        image: "/bature.jpg",
        clubName: "Medeama SC",
        clubLogo: "/Medeama_SC_logo.png",
        preferredFoot: "Right",
        height: "1.5",
        marketValue: "1M",
        contractExpiryDate: "2024/11/13",
      },
      {
        id: "a9ef4628-8eb5-426c-aa09-e8ed67d50c97",
        firstName: "Ishak",
        surName: "Shaibu",
        CountryCode: "GH",
        Nationality: "Ghana",
        Age: "14",
        position: "CAM",
        jerseyNumber: "15",
        image: "/OlderPlayer.jpg",
        clubName: "GoiCity SC",
        clubLogo: "/goicity.png",
        preferredFoot: "Left",
        height: "1.3",
        marketValue: "4K",
        contractExpiryDate: "2024/07/13",
        videos: [
          {
            src: "/shaibuJuggling.mp4",
            category: "skills",
            description: "juggling skills from trainning session",
          },
        ],
      },
      {
        id: "6fdf6a14-79f0-4531-a198-b61df87865f9",
        firstName: "Amos",
        surName: "Acheampong",
        Age: "30",
        position: "CDM",
        CountryCode: "GH",
        Nationality: "Ghana",
        jerseyNumber: "6",
        image: "/acheampong.webp",
        clubName: "Bechem united",
        clubLogo: "/Bechem_United_FC_logo.jpg",
        preferredFoot: "Right",
        height: "1.5",
        marketValue: "103K",
        contractExpiryDate: "2024/11/13",
      },
      {
        id: "9428749f-f0bd-4271-bc89-8e43c9e2ae01",
        firstName: "Anthony",
        surName: "Okachi",
        Age: "23",
        position: "ST",
        CountryCode: "NG",
        Nationality: "Nigeria",
        jerseyNumber: "6",
        image: "/Anthony_Achu_Okachi.jpeg",
        clubName: "Enyimba FC",
        clubLogo: "/Enyimba_International_F.C._logo.png",
        preferredFoot: "Right",
        height: "1.5",
        marketValue: "19K",
        contractExpiryDate: "2024/11/13",
      },
      {
        id: "26c2bb7a-ff7d-483d-967e-574d1763ccda",
        firstName: "Believer",
        surName: "Yeboah",
        Age: "12",
        position: "CM",
        CountryCode: "GH",
        Nationality: "Ghana",
        jerseyNumber: "18",
        image: "/BelieverPlayer.jpg",
        clubName: "GoiCity SC",
        clubLogo: "/goicity.png",
        preferredFoot: "Both",
        height: "1.5",
        marketValue: "2K",
        contractExpiryDate: "",
        videos: [
          {
            src: "/believerJuggling.mp4",
            category: "skills",
            description: "juggling skills from trainning session",
          },
        ],
      },
      {
        id: "dfda1364-2eb2-4562-a9c2-e7997b676eb7",
        firstName: "Stephen",
        surName: "Owusu",
        Age: "26",
        position: "ST",
        CountryCode: "GH",
        Nationality: "Ghana",
        jerseyNumber: "9",
        image: "/stephen owusu.webp",
        clubName: "Bofoakwa Tano SC",
        clubLogo: "/Bofoakwa_Tano.png",
        preferredFoot: "Left",
        height: "1.9",
        marketValue: "",
        contractExpiryDate: "2026/11/13",
      },
      {
        id: "fddb7f11-3152-459f-8dca-b153102829a2",
        firstName: "Solomon",
        surName: "Safo-Taylor",
        Age: "25",
        CountryCode: "GH",
        position: "CF",
        Nationality: "Ghana",
        jerseyNumber: "17",
        image: "/Solomon safo-taylor.jpg",
        clubName: "Asante Kotoko SC",
        clubLogo: "/Asante_Kotoko_SC_(logo).png",
        preferredFoot: "Both",
        height: "1.5",
        marketValue: "3M",
        contractExpiryDate: "2024/11/13",
      },
      {
        id: "6ff1258b-e0a8-467b-845f-454c62533af5",
        firstName: "Solomon",
        surName: "Agbasi",
        Age: "23",
        position: "GK",
        CountryCode: "GH",
        Nationality: "Ghana",
        jerseyNumber: "32",
        image: "/solomon agbasi.jpeg",
        clubName: "Dreams FC",
        clubLogo: "/Dreams_FC_logo.png",
        preferredFoot: "Right",
        height: "1.8",
        marketValue: "15K",
        contractExpiryDate: "2024/11/13",
      },
      {
        id: "1bb0af8a-8a1c-4e92-8d91-a548e613b9a7",
        firstName: "Pa Ebou",
        surName: "Dampha",
        Age: "20",
        position: "GK",
        CountryCode: "SN",
        Nationality: "Senegal",
        jerseyNumber: "32",
        image: "/Pa_Ebou_Dampha.jpeg",
        clubName: "Casa Sport FC",
        clubLogo: "/Casa_Sports_de_Ziguinchor.jpg",
        preferredFoot: "Right",
        height: "1.5",
        marketValue: "43K",
        contractExpiryDate: "2024/11/13",
      },
      {
        id: "d06d1473-83a9-497c-9c66-9acee4d7e4fb",
        firstName: "Daniel",
        surName: "Opare",
        Age: "33",
        position: "CB",
        CountryCode: "GH",
        Nationality: "Ghana",
        jerseyNumber: "4",
        image: "/opare.jpg",
        clubName: "Royal Antwerp FC",
        clubLogo: "/Royal_Antwerp_Football_Club_logo.png",
        preferredFoot: "Left",
        height: "1.5",
        marketValue: "",
        contractExpiryDate: "2024/10/03",
      },
    ],
    playersInAgency: [],
    selectedPlayerToCompareArray: [],
    playerSelectedByClubOrScoutInPlayerManagement: {},
    playerObjectSampleWithoutBasicInformation: {
      current_health: "Match Fit",
      videos: [],
      Achievements: [],
      Market_Value_History: [],
      Club_History: [],
      Statisitcs: [
        {
          Season: "23/24",
          General: {
            Games_Played: 0,
            Minutes_Played: 0,
            Starts: 0,
            "Subbed off": 0,
          },
          Defence: {
            Clearance: 0,
            Tackles: 0,
            Duels: 0,
            Aeriel_duels: 0,
            Blocks: 0,
            Interceptions: 0,
          },
          Attack: {
            Total_shots: 0,
            Shots_on_target: 0,
            Goals_Scored: 0,
            Conversion_rate: 0,
            Minutes_per_goal: 0,
            Header_goals: 0,
            Left_goals: 0,
            Right_goals: 0,
            Other_goals: 0,
            Goals_outside_the_box: 0,
            Goals_inside_the_box: 0,
            Goals_from_freekicks: 0,
          },
          Discipline: {
            Fouls_conceeded: 0,
            Fouls_won: 0,
            Yellow_cards: 0,
            Red_cards: 0,
          },
          Distribution: {
            Assists: 0,
            Pass_success_rate: 0,
            Long_passes_rate: 0,
            Opponent_half_pass_accuracy: 0,
            Own_half_pass_accuracy: 0,
            "Pass_direction_forward_%": 0,
            "Pass_direction_backward_%": 0,
            "Pass_direction_left_%": 0,
            "Pass_direction_right_%": 0,
            Total_passes: 0,
            Successful_passes: 0,
            Key_passes: 0,
            Total_passes_per_90_mins: 0,
          },
        },
        {
          Season: "22/23",
          General: {
            Games_Played: 0,
            Minutes_Played: 0,
            Starts: 0,
            "Subbed off": 0,
          },
          Defence: {
            Clearance: 0,
            Tackles: 0,
            Duels: 0,
            Aeriel_duels: 0,
            Blocks: 0,
            Interceptions: 0,
          },
          Attack: {
            Total_shots: 0,
            Shots_on_target: 0,
            Goals_Scored: 0,
            Conversion_rate: 0,
            Minutes_per_goal: 0,
            Header_goals: 0,
            Left_goals: 0,
            Right_goals: 0,
            Other_goals: 0,
            Goals_outside_the_box: 0,
            Goals_inside_the_box: 0,
            Goals_from_freekicks: 0,
          },
          Discipline: {
            Fouls_conceeded: 0,
            Fouls_won: 0,
            Yellow_cards: 0,
            Red_cards: 0,
          },
          Distribution: {
            Assists: 0,
            Pass_success_rate: 0,
            Long_passes_rate: 0,
            Opponent_half_pass_accuracy: 0,
            Own_half_pass_accuracy: 0,
            "Pass_direction_forward_%": 0,
            "Pass_direction_backward_%": 0,
            "Pass_direction_left_%": 0,
            "Pass_direction_right_%": 0,
            Total_passes: 0,
            Successful_passes: 0,
            Key_passes: 0,
            Total_passes_per_90_mins: 0,
          },
        },
        {
          Season: "21/22",
          General: {
            Games_Played: 0,
            Minutes_Played: 0,
            Starts: 0,
            "Subbed off": 0,
          },
          Defence: {
            Clearance: 0,
            Tackles: 0,
            Duels: 0,
            Aeriel_duels: 0,
            Blocks: 0,
            Interceptions: 0,
          },
          Attack: {
            Total_shots: 0,
            Shots_on_target: 0,
            Goals_Scored: 0,
            Conversion_rate: 0,
            Minutes_per_goal: 0,
            Header_goals: 0,
            Left_goals: 0,
            Right_goals: 0,
            Other_goals: 0,
            Goals_outside_the_box: 0,
            Goals_inside_the_box: 0,
            Goals_from_freekicks: 0,
          },
          Discipline: {
            Fouls_conceeded: 0,
            Fouls_won: 0,
            Yellow_cards: 0,
            Red_cards: 0,
          },
          Distribution: {
            Assists: 0,
            Pass_success_rate: 0,
            Long_passes_rate: 0,
            Opponent_half_pass_accuracy: 0,
            Own_half_pass_accuracy: 0,
            "Pass_direction_forward_%": 0,
            "Pass_direction_backward_%": 0,
            "Pass_direction_left_%": 0,
            "Pass_direction_right_%": 0,
            Total_passes: 0,
            Successful_passes: 0,
            Key_passes: 0,
            Total_passes_per_90_mins: 0,
          },
        },
        {
          Season: "20/21",
          General: {
            Games_Played: 0,
            Minutes_Played: 0,
            Starts: 0,
            "Subbed off": 0,
          },
          Defence: {
            Clearance: 0,
            Tackles: 0,
            Duels: 0,
            Aeriel_duels: 0,
            Blocks: 0,
            Interceptions: 0,
          },
          Attack: {
            Total_shots: 0,
            Shots_on_target: 0,
            Goals_Scored: 0,
            Conversion_rate: 0,
            Minutes_per_goal: 0,
            Header_goals: 0,
            Left_goals: 0,
            Right_goals: 0,
            Other_goals: 0,
            Goals_outside_the_box: 0,
            Goals_inside_the_box: 0,
            Goals_from_freekicks: 0,
          },
          Discipline: {
            Fouls_conceeded: 0,
            Fouls_won: 0,
            Yellow_cards: 0,
            Red_cards: 0,
          },
          Distribution: {
            Assists: 0,
            Pass_success_rate: 0,
            Long_passes_rate: 0,
            Opponent_half_pass_accuracy: 0,
            Own_half_pass_accuracy: 0,
            "Pass_direction_forward_%": 0,
            "Pass_direction_backward_%": 0,
            "Pass_direction_left_%": 0,
            "Pass_direction_right_%": 0,
            Total_passes: 0,
            Successful_passes: 0,
            Key_passes: 0,
            Total_passes_per_90_mins: 0,
          },
        },
        {
          Season: "19/20",
          General: {
            Games_Played: 0,
            Minutes_Played: 0,
            Starts: 0,
            "Subbed off": 0,
          },
          Defence: {
            Clearance: 0,
            Tackles: 0,
            Duels: 0,
            Aeriel_duels: 0,
            Blocks: 0,
            Interceptions: 0,
          },
          Attack: {
            Total_shots: 0,
            Shots_on_target: 0,
            Goals_Scored: 0,
            Conversion_rate: 0,
            Minutes_per_goal: 0,
            Header_goals: 0,
            Left_goals: 0,
            Right_goals: 0,
            Other_goals: 0,
            Goals_outside_the_box: 0,
            Goals_inside_the_box: 0,
            Goals_from_freekicks: 0,
          },
          Discipline: {
            Fouls_conceeded: 0,
            Fouls_won: 0,
            Yellow_cards: 0,
            Red_cards: 0,
          },
          Distribution: {
            Assists: 0,
            Pass_success_rate: 0,
            Long_passes_rate: 0,
            Opponent_half_pass_accuracy: 0,
            Own_half_pass_accuracy: 0,
            "Pass_direction_forward_%": 0,
            "Pass_direction_backward_%": 0,
            "Pass_direction_left_%": 0,
            "Pass_direction_right_%": 0,
            Total_passes: 0,
            Successful_passes: 0,
            Key_passes: 0,
            Total_passes_per_90_mins: 0,
          },
        },
      ],
    },
  },

  reducers: {
    setPlayersInAgencyArray: (state, action) => {
      state.playersInAgencyArray = action.payload;
    },
    setSelectedPlayerToCompareArray: (state, action) => {
      state.selectedPlayerToCompareArray = action.payload;
    },
    setPlayerSelectedByClubOrScoutInPlayerManagement: (state, action) => {
      state.playerSelectedByClubOrScoutInPlayerManagement = action.payload;
    },
    // setplayerObjectSampleWithoutBasicInformation: (state, action) => {
    //   state.playerSelectedByClubOrScoutInPlayerManagement = action.payload;
    // },
  },
});

export const selectPlayersInAgencyArray = (state) =>
  state.PlayersInAgencySlice.playersInAgencyArray;

export const selectPlayerToCompareArray = (state) =>
  state.PlayersInAgencySlice.selectedPlayerToCompareArray;

export const selectPlayerSelectedByClubOrScoutInPlayerManagement = (state) =>
  state.PlayersInAgencySlice.playerSelectedByClubOrScoutInPlayerManagement;

export const selectPlayerObjectSampleWithoutBasicInformation = (state) =>
  state.PlayersInAgencySlice.playerObjectSampleWithoutBasicInformation;

export const {
  setPlayersInAgencyArray,
  setSelectedPlayerToCompareArray,
  setPlayerSelectedByClubOrScoutInPlayerManagement,
  // setplayerObjectSampleWithoutBasicInformation,
} = PlayersInAgencySlice.actions;
export default PlayersInAgencySlice.reducer;
